packages:
  - workflow
  - model
  - ui
  - test
  - software
  - block

catalog:
  "@platforma-sdk/model": ^1.37.18
  "@platforma-sdk/ui-vue": ^1.37.18
  "@platforma-sdk/workflow-tengo": ^4.8.0
  "@platforma-sdk/block-tools": ^2.5.60
  "@platforma-sdk/test": ^1.37.17
  "@platforma-sdk/tengo-builder": ^2.1.11
  "@platforma-sdk/package-builder": ^2.16.2
  "@platforma-sdk/eslint-config": ^1.0.3
  "@milaboratories/graph-maker": ^1.1.128


  "@platforma-open/milaboratories.runenv-python-3": ^1.1.16
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.8
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^6.2.2
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.28.1
  "js-yaml": "^4.1.0"
  "sass-embedded": ^1.89.2
